config/routes.rb
Rails.application.routes.draw do
  root "brands#index"
  resources :brands, :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :products,  dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :Brand
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :current_brand, only: [:show, :edit, :update, :destroy]

    def index
      @brands = Brand.all
    end

    def show
      @brand = Brand.find(params[:id])
    end

    def new
      @brand = Brand.new
    end

    def create
      @brand = Brand.create(brand_params)

      redirect_to brand_path(@brand)
    end

    def edit

    end

    def update
      @brand.update(brand_params)

      redirect_to brand_path(@brand)
    end

    def destroy
      @brand.destroy

      redirect_to brands_path
    end

    private
    def brand_params
      params.require(:brand).permit(:name, :address, :phone)
    end

    def current_brand
      @brand = Brand.find(params[:id])
    end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :current_product, only: [:show, :edit, :update, :destroy]

      def index
        @products = Product.all
      end

      def show

      end

      def new
        @product = Product.new
      end

      def create
        @product = Product.create(product_params)

        redirect_to product_path(@product)
      end

      def edit

      end

      def update
        @product.update(product_params)

        redirect_to product_path(@product)
      end

      def destroy
        @product.destroy

        redirect_to products_path
      end

      private
      def product_params
        params.require(:product).permit(:name, :model, :Brand_id)
      end

      def current_product
        @product = Product.find(params[:id])
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/edit.html.erb
<h3>Marka Bilgileri Düzenle</h3>
<%= form_with model: @brand do |form| %>
  <p>Marka Adı: <%= form.text_field :name %></p>
  <p>Adres: <%= form.text_field :address %></p>
  <p>Telefon: <%= form.text_field :phone %></p>

  <%= form.submit %>
<% end %>

app/views/brands/index.html.erb
<h1>Markalar</h1>

<ul>
  <% @brands.each do |brand| %>
    <li>
      <%= link_to brand.name, brand%>
    </li>
  <% end %>
</ul>

<div><%= link_to 'Yeni Marka Oluştur', new_brand_path %></div>

app/views/brands/new.html.erb
<h3>Yeni Marka Ekle</h3>
<%= form_with model: @brand do |form| %>
  <p>Marka Adı: <%= form.text_field :name %></p>
  <p>Adres: <%= form.text_field :address %></p>
  <p>Telefon: <%= form.text_field :phone %></p>

  <%= form.submit %>
<% end %>

app/views/brands/show.html.erb
<h1>Marka: <%= @brand.name %></h1>
<%= link_to 'Marka Düzenle', edit_brand_path(@brand) %>
<p><b>Adres:</b> <%= @brand.address %></p>
<p><b>Telefon:</b> <%= @brand.phone %></p>


<h2>Markanın Ürünleri</h2>
<ul>
  <% @brand.products.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<br>
<p><%= link_to 'Yeni Ürün Oluştur', new_product_path %></p><br>
<p><%= link_to 'Markayı Sil', @brand, method: 'delete', data: { confirm: 'Emin misin?' }%></p><br>
<p><%= link_to 'Tüm Markaları Görüntüle', brands_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ETicaret</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h3>Ürün Düzenle</h3>
<%= form_with model: @product do |form| %>
  <p>Ürün Adı: <%= form.text_field :name %></p>
  <p>Ürün Modeli: <%= form.text_field :model %></p>

  <%= form.submit %>
<% end %>

app/views/products/index.html.erb
<h1>Ürünler</h1>
<ul><% @products.each do |product| %>
  <li>
    <%= link_to product.name, product_path(product) %>
  <% end %></li>
</ul>

<div><%= link_to 'Yeni Ürün Oluştur', new_product_path %></div>
<p><%= link_to 'Tüm Markaları Görüntüle', brands_path %></p>

app/views/products/new.html.erb
<h3>Yeni Ürün Ekle</h3>
<%= form_with model: @product do |form| %>
  <p>Ürün Adı: <%= form.text_field :name %></p>
  <p>Ürün Modeli: <%= form.text_field :model %></p>
  
  <p>Brand: <%= form.select :Brand_id, Brand.all.map { |brand| [ brand.name, brand.id ] } %></p>

  <%= form.submit %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<%= link_to 'Ürünü Düzenle', edit_product_path(@product) %>
<p><b>Ürün Adı:</b> <%= @product.name %></p>
<p><b>Ürün Modeli:</b> <%= @product.model %></p>

<h4>Brand: <%= link_to @product.Brand.name, brand_path(@product.Brand) %></h4>

<p><%= link_to 'Ürünü Sil', @product, method: 'delete', data: { confirm: 'Emin misin?' }%></p>
<p><%= link_to 'Tüm Ürünleri Görüntüle', products_path %></p>